import type { Metadata } from "next";
import { Geist, Geist_Mono, Quicksand, Urbanist } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const quicksand = Quicksand({
  subsets: ["latin"],
  variable: "--font-quicksand", // Đặt tên biến CSS
  display: "swap",
});

const urbanist = Urbanist({
  subsets: ["latin"],
  variable: "--font-urbanist", // Đặt tên biến CSS
  display: "swap",
});

export const metadata: Metadata = {
  title: "Dozy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${quicksand.variable} ${urbanist.variable} antialiased`}
        suppressHydrationWarning
      >

        {children}
      </body>
    </html>
  );
}
